name: Building Docker Image

on:
  workflow_dispatch:

jobs:

  buildimage:
    runs-on: ubuntu-latest

    steps:
    - name: Building image ... 
      run: |
        echo "${{secrets.DOCKER_HUB_TOKEN}}" | docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" --password-stdin docker.io
        
        docker build . --file dockerfile.build --tag docker.io/${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_REPOSITORY}}:$GITHUB_SHA
            
        docker push docker.io/${{secrets.DOCKER_HUB_USERNAME}}/${{secrets.DOCKER_HUB_REPOSITORY}}:$GITHUB_SHA
